/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package trademanager;
import Classes.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class createCustomerSection extends javax.swing.JDialog implements Observable {
        DefaultTableModel customerTable;
    /**
     * Creates new form createCustomer1
     */
    public createCustomerSection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        customerTable = (DefaultTableModel) customerTableList.getModel();
        Warehouse.getInstance().registerObservable(this);
        customerTable.setRowCount(0);
        Warehouse.getInstance().registerObservable(this);
        
       // modelTable = (DefaultTableModel) productListTable.getModel();
       // Warehouse.getInstance().registerObservable(this);
       // modelTable.setRowCount(0);
       // Warehouse.getInstance().registerObservable(this); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerTableList = new javax.swing.JTable();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        customerTableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "F_Name", "L_Name", "EMail", "Phone", "Balance", "Status"
            }
        ));
        jScrollPane1.setViewportView(customerTableList);
        if (customerTableList.getColumnModel().getColumnCount() > 0) {
            customerTableList.getColumnModel().getColumn(0).setMinWidth(30);
            customerTableList.getColumnModel().getColumn(0).setPreferredWidth(30);
            customerTableList.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        addButton.setBackground(new java.awt.Color(51, 204, 255));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.setAlignmentX(0.5F);
        addButton.setBorderPainted(false);
        addButton.setOpaque(true);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        editCustomerSection.main(null);
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        createCustomerSection addCustomer = new createCustomerSection(MainWindow.getInstance(), true);
        addCustomer.setLocationRelativeTo(MainWindow.getInstance());
        addCustomer.pack();
        addCustomer.setVisible(true);
        
         //addProductSection addProduct = new addProductSection(MainWindow.getInstance(), true);
        //addProduct.setLocationRelativeTo(MainWindow.getInstance() );
        //addProduct.pack();
        //addProduct.setVisible(true); 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createCustomerSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createCustomerSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createCustomerSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createCustomerSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
    }
    
    @Override
    public void onUpdate() {
        customerTable.setRowCount(0);
        
        for (int i = 0; i < Warehouse.getInstance().getCustomerCount(); i++) {
            Customer customer = Warehouse.getInstance().getCustomer(i);
            customerTable.addRow(new Object[] { i,  customer.getFirstName(), customer.getLastName(), customer.getGmail(), customer.getPhone(), customer.getBalance(), customer.getStatus() });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTable customerTableList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
